kind: PersistentVolume
apiVersion: v1
metadata:
 name: nginx-pv
 namespace: nginx # volume should be created in the same namespace as the pod
spec:
 capacity:
  storage: 1Gi
 accessModes:
 - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: local-storage
 local:
  path: /data/nginx
 nodeAffinity:
  required:
   nodeSelectorTerms:
   - matchExpressions:
     - key: kubernetes.io/hostname
       operator: In
       values:
       - tws-cluster-worker
