kind: Service
apiVersion: v1
metadata:
  name: apache-service
  namespace: apache
spec:
  type: ClusterIP
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80 # clusterIP port
      targetPort: 80 # containerPort in deployment.yml