kind: Service
apiVersion: v1
metadata:
 name: nginx-service
 namespace: nginx
spec:
 type: ClusterIP
 selector:
  app: nginx
 ports:
 - port: 80
   targetPort: 80


# kubectl port-forward service/nginx-service 8080:80 -n nginx

# try this in your browser: http://localhost:8080